**Assigning Subsequent Rows to Matrix first row elements**

Input : test_list = [[5, 8, 10], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
Output : {5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]}
Explanation : 5 paired with 2nd row, 8 with 3rd and 10 with 4th

In [1]:
import numpy as np

arr = np.array([[5, 8, 10], [2, 0, 9], [5, 4, 2], [2, 3, 9]])
print(arr)

[[ 5  8 10]
 [ 2  0  9]
 [ 5  4  2]
 [ 2  3  9]]


In [4]:
a= arr[0]
b= arr[1:]
c= dict()
for i in range(len(a)):
    c[a[i]] = b[i]

print(c)

{np.int64(5): array([2, 0, 9]), np.int64(8): array([5, 4, 2]), np.int64(10): array([2, 3, 9])}


**Adding and Subtracting Matrices in Python**

Suppose we have two matrices A and B.
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

then we get
A+B = [[5,7],[9,11]]
A-B = [[-3,-3],[-3,-3]]

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

add = []
sub = []

for i in range(len(a)):
    ans = []
    for j in range(len(a[i])):
        ans.append(a[i][j] + b[i][j])

    add.append(ans)

for i in range(len(a)):
    ans = []
    for j in range(len(a[i])):
        ans.append(a[i][j] - b[i][j])

    sub.append(ans)

print(add)
print(sub)

[[np.int64(5), np.int64(7)], [np.int64(9), np.int64(11)]]
[[np.int64(-3), np.int64(-3)], [np.int64(-3), np.int64(-3)]]


In [8]:
print(np.add(a,b))

[[ 5  7]
 [ 9 11]]


In [9]:
print(np.subtract(a, b))

[[-3 -3]
 [-3 -3]]


**Group similar elements into Matrix**
Input : test_list = [1, 3, 4, 4, 2, 3]
Output : [[1], [2], [3, 3], [4, 4]]

In [10]:
a= np.array([1, 3, 4, 4, 2, 3])
print(a)

[1 3 4 4 2 3]


In [11]:
res = []
for i in a:
    found = False
    for j in range(len(res)):
        if i in res[j]:
            res[j].append(i)
            found = True
            break
    if not found:
        res.append([i])

print(res)
    

[[np.int64(1)], [np.int64(3), np.int64(3)], [np.int64(4), np.int64(4)], [np.int64(2)]]


**Row-wise element Addition in Tuple Matrix**

input : test_list = [[('Gfg', 3)], [('best', 1)]] cus_eles = [1, 2]
Output : [[('Gfg', 3, 1)], [('best', 1, 2)]]

In [14]:
test_list = [[('Gfg', 3)], [('best', 1)]]
cus_eles = [1, 2]

In [15]:
result_list = []
for i, row in enumerate(test_list):
    new_row = [(tup + (cus_eles[i],)) for tup in row]
    result_list.append(new_row)

print(result_list)

[[('Gfg', 3, 1)], [('best', 1, 2)]]


**Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even**
input: 2
Output: 1 2
4 3
Explanation: Here sum of 1+3=4 is even and 2+4=6 is even

In [18]:
def generate_matrix(n):
    matrix = [[0]* n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            matrix[i][j] = i + j + 1

    print(matrix)

generate_matrix(2)

[[1, 2], [2, 3]]


In [ ]:
1 2 3
4 5 6
7 8 9

